export const TYPES = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_ERROR: 'AUTH_LOGIN_ERROR',
  CHECKING_AUTH: 'CHECKING_AUTH',

  //cart types
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
  HADLE_TOGGLE_CART: 'TOGGLE_HIDDEN_CART',



  SET_CATEGORY: 'SET_CATEGORY',
  REMOVE_CATEGORY:'REMOVE_CATEGORY',
  SET_SEARCH: 'SET_SEARCH',
  CLEAR_SEARCH: 'CLEAR_SEARCH',
};
