export const TYPES = {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_ERROR: 'AUTH_LOGIN_ERROR',
  CHECKING_AUTH: 'CHECKING_AUTH',

  //cart types
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
  HADLE_TOGGLE_CART: 'TOGGLE_HIDDEN_CART',

  // category types
  SET_CATEGORY: 'SET_CATEGORY',
};
